name: Build config-sync-init oci image

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'oci/config-sync-init/**'
  workflow_dispatch:

jobs:
  config-sync-init-build:
    uses: ./.github/workflows/oci-image-pipeline.yml
    with:
      SUB_DIR: 'oci/config-sync-init'
      IMAGE_REGISTRY_PREFIX: 'us-central1-docker.pkg.dev/cap-prod-gke-6cc6/artifreg-devops-prod/oci'
      IMAGE_NAME: 'config-sync-init'
      RELEASE_IMAGE: false
    secrets: inherit
